[database.mysql]
username = "admin"
password = "gAAAAABkKoPWU0bJwSREcQ01egg9091Xjbvs_TEaIg_7ZmxINB95kYRAKmdylqtaunYGkTFSa7HvV-G2vBk97m3fdbm63slTb1j0z-dypRthJarPbgzvhUg="
endpoint = "mas-v2-database.cvemd7kvhgtq.ap-northeast-2.rds.amazonaws.com"
port = 3306
database_name = "mas"

#[oauth2.google]
#redirect_uri = "http://localhost:5500/login/"
#javascript_origins = [
#    "http://localhost:5500",
#]
[oauth2.google]
client_id = "875870111546-ub0phvh6rcumm261nknla970lgpf5uve.apps.googleusercontent.com"
project_id = "mas-server-382806"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_secret = "gAAAAABkMmQZNehPUGPL2hExWa5MxSRyvewu3QhyyD8quLFsvqbNz-2UC-rSZyiq_-qRfWz8mY8Y67rorP06sjAy9m9V7ZHiF-4BooJVLXsDAv5Nkhct1BoIPYPmRA1k47ERIVleJtRA"
scopes=[
    "https://www.googleapis.com/auth/userinfo.email",
    "openid",
    "https://www.googleapis.com/auth/userinfo.profile",
]
redirect_uri = "http://localhost:5500/login/"
javascript_origins = [
    "http://localhost:5500",
]
